server:
  port: 0 # 0번 port를 사용하겠다는 의가 아님. 사용되지 않는 port번호를 임의로 할당해달라는 의미...
  
spring:
  application:
    name: order-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
      
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/artdb2?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
    username: tj705
    password: tj705
    

      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # 유레카 서버에 등록
    fetch-registry: true # 주기적으로 다른 인스턴스의 데이터를 받아와서 갱신
    service-url:
      defaultZone: http://localhost:8761/eureka # 유레카 서버의 주소 정보

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
